### ISSUE TITLE
Error: account created but then immediately deleted

### ISSUE THREAD

**Issue by webidfuture** [maidsafe/safe-web-id-manager-js#18]
I turned on the "toggle experiments" option and the account is correctly created but then it is immediately deleted and the list is empty.

![error](https://user-images.githubusercontent.com/46053292/50352274-11248880-0545-11e9-8049-c42f1ffcb7de.PNG)

**Comment by bochaco** [comment]
hey @webidfuture , thanks a lot for taking the time to report this. Could you please share what you see in the devtools console of this page (open it with ctrl+alt+I) when this happens?

**Comment by webidfuture** [comment]
Hi @bochaco ! Tried again this time and it works!
Just a question. When i click my webid, this screen appears
![problem](https://user-images.githubusercontent.com/46053292/50841994-24698d80-1366-11e9-8fc0-6531c8d79153.PNG)

**Comment by hunterlester** [comment]
@webidfuture That's your WebID in RDF, represented in [Turtle syntax](https://www.w3.org/TR/turtle/).

**Comment by webidfuture** [comment]
And it's ok that it's showed up or something else should appear?

**Comment by webidfuture** [comment]
alright. Thanks!
