### ISSUE TITLE
Slash after # in WebID seems wrong

### ISSUE THREAD

**Issue by theWebalyst** [maidsafe/safe-web-id-manager-js#4]
The URI for the WebID I created is given as `safe://webid.safeandsolid/#/me` which is unusual and possibly not valid. I suggest generating WebIDs with a text only fragment such as:

`safe://webid.safeandsolid/#me`

Solid WebIDs usually point to a fragment in a profile file such as:

`safe://webid.safeandsolid/public/card#me`

**Comment by joshuef** [comment]
I think this is actually Peruse's fault.
At least in the rdf graph this is `#me`, so I'll have to have a peek at Peruse's uri resolution. 

Will post back when confirmed.

**Comment by joshuef** [comment]
This is indeed peruse's URL handling. 

https://github.com/joshuef/peruse/commit/6b1f172fc8e10c337c48c5c0a1dfeec936b86660

sorts this.
